import { Image } from '@chakra-ui/image'
import { Flex, Heading } from '@chakra-ui/layout'
import Head from 'next/head'
// import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <>
      <Head>
        <title>BAYB CAKES</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Flex h='100vh' alignItems='center' justifyContent='center' bg='blackAlpha.500'>
        <Heading>
          <Image src='/images/bayb-cakes-transparent.png' boxSize='sm' />
        </Heading>
      </Flex>
    </>
  )
}
